#!/usr/bin/env bash
# Idempotent environment bootstrap for Easy Cash (ERP).
# Runs after the repository is checked out. Safe to run repeatedly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DB_NAME="easy_cash"
DB_USER="easy_cash"
DB_PASS="easy_cash_dev"
DB_URL="mysql://${DB_USER}:${DB_PASS}@127.0.0.1:3306/${DB_NAME}"

echo "==> Installing Node dependencies (pnpm)"
corepack enable >/dev/null 2>&1 || true
pnpm install --frozen-lockfile

echo "==> Ensuring MySQL server is installed"
if ! command -v mysqld >/dev/null 2>&1; then
  sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
fi

echo "==> Starting MySQL and waiting for it to accept connections"
sudo service mysql start || true
for i in $(seq 1 60); do
  if sudo mysqladmin ping >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "==> Creating database and application user (idempotent)"
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'127.0.0.1';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

if [ ! -f .env ]; then
  echo "==> Writing local development .env"
  cat > .env <<'ENVEOF'
# Local development environment (Cloud Agent) — generated by .cursor/install.sh
NODE_ENV=development

MYSQL_DATABASE=easy_cash
MYSQL_USER=easy_cash
MYSQL_PASSWORD=easy_cash_dev
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
DATABASE_URL=mysql://easy_cash:easy_cash_dev@127.0.0.1:3306/easy_cash

APP_PORT=3000
PORT=3000
APP_URL=http://localhost:3000

# Dev-only long random values so the weak-secret guard passes locally.
JWT_SECRET=dev-local-jwt-secret-9f2c1a7b4e6d8h0k3m5n7q
ENCRYPTION_KEY=dev-local-encryption-key-1a3c5e7g9i0k2m4o6q8s
SHOPE_INTEGRATION_SECRET=dev-local-shope-integration-secret-4b6d8f0h2j
ALLOW_WEAK_SECRETS=1

VITE_APP_TITLE=Easy Cash

# Disable optional external integrations for local dev.
OLLAMA_ENABLED=0
PAYMOB_ALLOW_UNSIGNED=1
ENVEOF
fi

echo "==> Applying database migrations"
DATABASE_URL="${DB_URL}" node scripts/run-migrations.mjs

echo "==> Install complete"
