/** تسميات عربية لأعمدة التقارير الديناميكية */
export const REPORT_COLUMN_LABELS: Record<string, string> = {
  documentNumber: "رقم المستند",
  entryNumber: "رقم القيد",
  date: "التاريخ",
  partyCode: "كود الطرف",
  partyName: "العميل / المورد",
  customerName: "العميل",
  vendorName: "المورد",
  supplierName: "المورد",
  branchName: "الفرع",
  warehouseName: "المخزن",
  repName: "المندوب",
  areaName: "المنطقة",
  currencyCode: "العملة",
  exchangeRate: "سعر الصرف",
  foreignTotal: "الإجمالي (عملة أجنبية)",
  subtotal: "المجموع الفرعي",
  discount: "الخصم",
  tax: "الضريبة",
  total: "الإجمالي (ج.م)",
  paid: "المدفوع",
  remaining: "المتبقي",
  status: "الحالة",
  paymentType: "نوع الدفع",
  checkNumber: "رقم الشيك",
  dueDate: "تاريخ الاستحقاق",
  amount: "المبلغ",
  code: "الكود",
  name: "الاسم",
  phone: "الهاتف",
  email: "البريد",
  balance: "الرصيد",

  // كشف حساب عميل بالأصناف — أعمدة ميجا (PDF 2026-09-13)
  outQty: "صادر كمية",
  outPrice: "صادر سعر",
  outTotal: "صادر اجمالي",
  inQty: "وارد كمية",
  inPrice: "وارد سعر",
  inTotal: "وارد اجمالي",
  cashBankIn: "استلام نقدية / ايداع بنكي",
  cashBankOut: "صرف نقدية / سحب بنكي",
  checkCollected: "شيك محصل / تحت التحصيل",
  checkRejected: "شيك مرفوض",
  otherOps: "عمليات اخرى",

  creditLimit: "حد الائتمان",
  category: "التصنيف",
  metric: "المؤشر",
  value: "القيمة",
  period: "الفترة",
  journalReference: "مرجع القيد",
  postedDepreciation: "إهلاك مرحّل",
  bookAccumulated: "مجمّع دفتري",
  monthlyTheoretical: "إهلاك شهري نظري",
  lastPostedPeriod: "آخر فترة مرحّلة",
  lastJournalRef: "آخر قيد",
  lineAmount: "مبلغ السطر",
  assetCode: "كود الأصل",
  assetName: "اسم الأصل",
  totalAmount: "إجمالي الفترة",
  source: "المصدر",
  itemCode: "كود الصنف",
  itemName: "اسم الصنف",
  quantity: "الكمية",
  profit: "الربح",
  month: "الشهر",
  channel: "القناة",
  commission: "العمولة",
  commissionRate: "نسبة العمولة",
  totalSales: "إجمالي المبيعات",
  totalPurchases: "إجمالي المشتريات",
  totalPaid: "إجمالي المدفوع",
  totalPaidCash: "مدفوعات نقدية",
  totalCollected: "إجمالي التحصيل",
  invoiceCount: "عدد الفواتير",
  invoicesCount: "عدد الفواتير",
  customersCount: "عدد العملاء",
  suppliersCount: "عدد الموردين",
  warehousesCount: "عدد المخازن",
  salesTotal: "إجمالي المبيعات",
  costTotal: "إجمالي التكلفة",
  salesPaid: "مبيعات مدفوعة",
  salesRemaining: "مبيعات متبقية",
  purchasesTotal: "إجمالي المشتريات",
  salesInvoicesCount: "فواتير بيع",
  purchasesInvoicesCount: "فواتير شراء",
  collectionsTotal: "التحصيلات",
  netSalesPurchases: "صافي (بيع − شراء)",
  address: "العنوان",
  description: "الوصف",
  isActive: "نشط",
  count: "العدد",
  collectionsCount: "عدد التحصيلات",
  accountCode: "كود الحساب",
  accountName: "اسم الحساب",
  debit: "مدين",
  credit: "دائن",
  costCenter: "مركز التكلفة",
  // ميزان المراجعة — أعمدة ميجا من ملف التصدير «ميزان المراجعة.xlsx»
  // (كود، اسم، أول المدة م/د، حركة م/د، آخر المدة م/د)
  openingDebit: "أول المدة مدين",
  openingCredit: "أول المدة دائن",
  periodDebit: "حركة مدين",
  periodCredit: "حركة دائن",
  closingDebit: "آخر المدة مدين",
  closingCredit: "آخر المدة دائن",
  openingBalance: "رصيد افتتاحي",
  openingBalanceDate: "تاريخ الرصيد الافتتاحي",
  closingBalance: "رصيد ختامي",
  label: "البند",
  type: "النوع",
  direction: "الاتجاه",
  number: "الرقم",
  productName: "المنتج",
  orderNumber: "رقم الأمر",
  purchasePrice: "سعر الشراء",
  currentValue: "القيمة الحالية",
  bookValue: "القيمة الدفترية",
  saleAmount: "مبلغ البيع",
  gainLoss: "ربح / خسارة",
  buyer: "المشتري",
  purchaseDate: "تاريخ الشراء",
  saleDate: "تاريخ البيع",
  notes: "ملاحظات",
  depreciationRate: "نسبة الإهلاك",
};

export function reportColumnLabel(key: string) {
  return REPORT_COLUMN_LABELS[key] || key;
}

/** أعمدة رقمية تُجمَّع في صف الإجمالي */
export const REPORT_TOTAL_COLUMNS = new Set([
  "total", "subtotal", "discount", "tax", "paid", "remaining", "amount",
  "quantity", "profit", "commission", "foreignTotal", "balance",
  "totalSales", "totalPurchases", "totalPaid", "totalPaidCash", "totalCollected",
  "salesTotal", "salesPaid", "salesRemaining", "purchasesTotal", "collectionsTotal",
  "netSalesPurchases", "invoiceCount", "invoicesCount", "customersCount",
  "suppliersCount", "warehousesCount",
  "salesInvoicesCount", "purchasesInvoicesCount", "count", "collectionsCount",
  "costTotal",
  "debit", "credit", "value", "lineAmount", "totalAmount", "postedDepreciation",
  "bookAccumulated", "monthlyTheoretical", "purchasePrice", "currentValue",
  "bookValue", "saleAmount", "gainLoss",
  "openingDebit", "openingCredit", "periodDebit", "periodCredit",
  "closingDebit", "closingCredit",
]);
