/** تسميات عربية لأعمدة التقارير الديناميكية */
export const REPORT_COLUMN_LABELS: Record<string, string> = {
  lineLabel: "البيان",
  documentNumber: "رقم المستند",
  entryNumber: "رقم القيد",
  date: "التاريخ",
  partyCode: "كود الطرف",
  partyName: "العميل / المورد",
  customerName: "العميل",
  vendorName: "المورد",
  supplierName: "المورد",
  branchName: "الفرع",
  warehouseName: "المخزن",
  repName: "المندوب",
  areaName: "المنطقة",
  currencyCode: "العملة",
  exchangeRate: "سعر الصرف",
  foreignTotal: "الإجمالي (عملة أجنبية)",
  subtotal: "المجموع الفرعي",
  discount: "الخصم",
  tax: "الضريبة",
  additions: "اضافات",
  expenses: "المصروفات",
  referenceNumber: "رقم المرجع",
  salesQty: "مبيعات",
  purchaseQty: "مشتريات",
  returnQty: "مردود",
  unitName: "وحدة القياس",
  unitPrice: "سعر الوحدة",
  net: "الصافي",
  total: "الإجمالي (ج.م)",
  paid: "المدفوع",
  remaining: "المتبقي",
  status: "الحالة",
  paymentType: "نوع الدفع",
  checkNumber: "رقم الشيك",
  dueDate: "تاريخ الاستحقاق",
  amount: "المبلغ",
  code: "الكود",
  name: "الاسم",
  phone: "الهاتف",
  email: "البريد",
  balance: "الرصيد",

  // كشف حساب عميل بالأصناف — أعمدة ميجا (PDF 2026-09-13)
  outQty: "صادر كمية",
  outPrice: "صادر سعر",
  outTotal: "صادر اجمالي",
  inQty: "وارد كمية",
  inPrice: "وارد سعر",
  inTotal: "وارد اجمالي",
  cashBankIn: "استلام نقدية / ايداع بنكي",
  cashBankOut: "صرف نقدية / سحب بنكي",
  checkCollected: "شيك محصل / تحت التحصيل",
  checkRejected: "شيك مرفوض",
  otherOps: "عمليات اخرى",

  creditLimit: "حد الائتمان",
  category: "التصنيف",
  metric: "المؤشر",
  value: "القيمة",
  period: "الفترة",
  journalReference: "مرجع القيد",
  postedDepreciation: "إهلاك مرحّل",
  bookAccumulated: "مجمّع دفتري",
  monthlyTheoretical: "إهلاك شهري نظري",
  lastPostedPeriod: "آخر فترة مرحّلة",
  lastJournalRef: "آخر قيد",
  lineAmount: "مبلغ السطر",
  assetCode: "كود الأصل",
  assetName: "اسم الأصل",
  totalAmount: "إجمالي الفترة",
  source: "المصدر",
  itemCode: "كود الصنف",
  itemName: "اسم الصنف",
  quantity: "الكمية",
  profit: "الربح",
  month: "الشهر",
  channel: "القناة",
  commission: "العمولة",
  commissionRate: "نسبة العمولة",
  totalSales: "إجمالي المبيعات",
  totalPurchases: "إجمالي المشتريات",
  totalPaid: "إجمالي المدفوع",
  totalPaidCash: "مدفوعات نقدية",
  totalCollected: "إجمالي التحصيل",
  invoiceCount: "عدد الفواتير",
  invoicesCount: "عدد الفواتير",
  customersCount: "عدد العملاء",
  suppliersCount: "عدد الموردين",
  warehousesCount: "عدد المخازن",
  salesTotal: "إجمالي المبيعات",
  costTotal: "إجمالي التكلفة",
  salesPaid: "مبيعات مدفوعة",
  salesRemaining: "مبيعات متبقية",
  purchasesTotal: "إجمالي المشتريات",
  salesInvoicesCount: "فواتير بيع",
  purchasesInvoicesCount: "فواتير شراء",
  collectionsTotal: "التحصيلات",
  netSalesPurchases: "صافي (بيع − شراء)",
  address: "العنوان",
  description: "الوصف",
  isActive: "نشط",
  count: "العدد",
  collectionsCount: "عدد التحصيلات",
  accountCode: "كود الحساب",
  accountName: "اسم الحساب",
  debit: "مدين",
  credit: "دائن",
  costCenter: "مركز التكلفة",
  // ميزان المراجعة — أعمدة ميجا من ملف التصدير «ميزان المراجعة.xlsx»
  // (كود، اسم، أول المدة م/د، حركة م/د، آخر المدة م/د)
  openingDebit: "أول المدة مدين",
  openingCredit: "أول المدة دائن",
  periodDebit: "حركة مدين",
  periodCredit: "حركة دائن",
  closingDebit: "آخر المدة مدين",
  closingCredit: "آخر المدة دائن",
  openingBalance: "رصيد افتتاحي",
  openingBalanceDate: "تاريخ الرصيد الافتتاحي",
  closingBalance: "رصيد ختامي",
  label: "البند",
  type: "النوع",
  direction: "الاتجاه",
  number: "الرقم",
  productName: "المنتج",
  orderNumber: "رقم الأمر",
  purchasePrice: "سعر الشراء",
  currentValue: "القيمة الحالية",
  bookValue: "القيمة الدفترية",
  saleAmount: "مبلغ البيع",
  gainLoss: "ربح / خسارة",
  buyer: "المشتري",
  purchaseDate: "تاريخ الشراء",
  saleDate: "تاريخ البيع",
  notes: "ملاحظات",
  depreciationRate: "نسبة الإهلاك",
};

export function reportColumnLabel(key: string) {
  return REPORT_COLUMN_LABELS[key] || key;
}

/**
 * تسميات أعمدة ميجا حسب التقرير — من PDF بعد عرض (فترة قصيرة).
 * لا اختراع: فقط ما ظهر في رؤوس جداول ميجا.
 */
const MEGA_REPORT_COLUMN_LABELS: Record<string, Record<string, string>> = {
  // البيع — صف الفاتورة: مسلسل التاريخ العميل الاجمالي الخصم الضريبة اضافات الصافي المصروفات المستحق تحصيله
  "accountingreports-sales": {
    documentNumber: "مسلسل",
    date: "التاريخ",
    partyName: "العميل",
    subtotal: "الاجمالي",
    discount: "الخصم",
    tax: "الضريبة",
    additions: "اضافات",
    total: "الصافي",
    expenses: "المصروفات",
    remaining: "المستحق تحصيله",
  },
  // الشراء — صف الفاتورة: مسلسل رقم المرجع التاريخ المورد الاجمالي الخصم الضريبة الصافي المستحق سداده
  "accountingreports-purchases": {
    documentNumber: "مسلسل",
    referenceNumber: "رقم المرجع",
    date: "التاريخ",
    partyName: "المورد",
    subtotal: "الاجمالي",
    discount: "الخصم",
    tax: "الضريبة",
    total: "الصافي",
    remaining: "المستحق سداده",
  },
  // المبيعات بالعملاء
  "accountingreports-customerssales": {
    documentNumber: "مسلسل",
    areaName: "المنطقة",
    customerName: "العميل",
    total: "الاجمالي",
    discount: "الخصومات",
    tax: "الضرائب",
    additions: "اضافات",
    net: "الصافي",
    remaining: "المديونية",
    lastSaleDate: "اخر بيع",
    lastCollectionDate: "اخر تحصيل",
  },
  // المشتريات بالموردين
  "accountingreports-vendorspurchases": {
    documentNumber: "مسلسل",
    vendorName: "المورد",
    total: "الاجمالي",
    discount: "الخصومات",
    tax: "الضرائب",
    net: "الصافي",
    remaining: "المديونية",
    lastPurchaseDate: "اخر شراء",
    lastPaymentDate: "اخر سداد",
  },
  // المبيعات بالأصناف
  "accountingreports-grosscustomersalesbyitems": {
    itemName: "الصنف",
    salesQty: "مبيعات",
    returnQty: "مردود",
    quantity: "الكمية",
    unitName: "وحدة القياس",
    unitPrice: "سعر الوحدة",
    discount: "الخصم",
    total: "القيمة",
  },
  // المشتريات بالأصناف
  "accountingreports-grossvendorpurchasesbyitems": {
    itemName: "الصنف",
    purchaseQty: "مشتريات",
    returnQty: "مردود",
    quantity: "الكمية",
    unitName: "وحدة القياس",
    unitPrice: "سعر الوحدة",
    discount: "الخصم",
    total: "القيمة",
  },
  // —— موجة 2: من PDF ميجا (artifacts/mega-wave2-sales/pdf) ——
  "accountingreports-customerstatment": {
    date: "التاريخ",
    debit: "مدين",
    credit: "دائن",
    balance: "الرصيد",
    description: "الوصف",
    exchangeRate: "سعر الصرف",
    documentNumber: "رقم المستند",
    entryNumber: "رقم القيد",
  },
  "accountingreports-vendorstatment": {
    date: "التاريخ",
    debit: "مدين",
    credit: "دائن",
    balance: "الرصيد",
    description: "الوصف",
    exchangeRate: "سعر الصرف",
    documentNumber: "رقم المستند",
    entryNumber: "رقم القيد",
  },
  "accountingreports-customerslist": {
    name: "الاسم",
    balance: "الرصيد",
    creditLimit: "الحد الائتمانى",
    areaName: "المنطقة",
    documentNumber: "مسلسل",
    phone: "التليفون",
    address: "العنوان",
    category: "الفئة",
    debtAge: "عمر الدين",
  },
  "accountingreports-vendorslist": {
    name: "الاسم",
    balance: "الرصيد",
    phone: "التليفون",
    address: "العنوان",
    category: "الفئة",
    maxDebtAge: "اقصى عمر للدين",
  },
  "accountingreports-customerssummary": {
    name: "الاسم",
    sales: "مبيعات",
    salesReturns: "مردود مبيعات",
    collections: "تحصيلات",
    otherOps: "عمليات اخرى",
    balanceToDate: "الرصيد حتى تاريخه",
    previousBalance: "رصيد سابق",
    documentNumber: "مسلسل",
    netSales: "صافى مبيعات",
  },
  "accountingreports-areassummary": {
    name: "الاسم",
    sales: "مبيعات",
    salesReturns: "مردود مبيعات",
    collections: "تحصيلات",
    otherOps: "عمليات اخرى",
    balanceToDate: "الرصيد حتى تاريخه",
    previousBalance: "رصيد سابق",
    documentNumber: "مسلسل",
    netSales: "صافى مبيعات",
  },
  "accountingreports-vendorssummary": {
    name: "الاسم",
    purchases: "مشتريات",
    purchaseReturns: "مردود مشتريات",
    payments: "سداد",
    otherOps: "عمليات اخرى",
    balanceToDate: "الرصيد حتى تاريخه",
    previousBalance: "رصيد سابق",
    documentNumber: "مسلسل",
    netPurchases: "صافى مشتريات",
  },
  "accountingreports-lastprices": {
    itemName: "الصنف",
    lastSalePrice: "اخر سعر بيع",
    lastPurchasePrice: "اخر سعر شراء",
    category: "الفئة",
    barcode: "الباركود",
    documentNumber: "مسلسل",
    lastSaleDiscount: "اخر خصم بيع",
    lastPurchaseDiscount: "اخر خصم شراء",
  },
  "accountingreports-matureinvoices": {
    date: "التاريخ",
    documentNumber: "مسلسل",
    dueDate: "تاريخ الاستحقاق",
    invoiceNet: "صافى الفاتورة",
    collectedPaid: "تحصيل / سداد",
    returns: "مردودات",
    netDue: "صافى الاستحقاق",
    repName: "المندوب",
    lastSettlement: "اخر سداد / تحصيل",
  },
  "accountingreports-maturereceipts": {
    date: "التاريخ",
    documentNumber: "مسلسل",
    dueDate: "تاريخ الاستحقاق",
    invoiceNet: "صافى الفاتورة",
    collectedPaid: "تحصيل / سداد",
    returns: "مردودات",
    netDue: "صافى الاستحقاق",
    repName: "المندوب",
    lastSettlement: "اخر سداد / تحصيل",
  },
  "accountingreports-monthlysalesbyitems": {
    itemName: "الصنف",
    total: "المجموع",
  },
  "accountingreports-monthlysalesbyitemstotals": {
    itemName: "الصنف",
    total: "المجموع",
  },
  "accountingreports-salesorders": {
    value: "القيمة",
    unitName: "وحده القياس",
    itemName: "الصنف",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    batchNumber: "رقم التشغيلة",
    discount: "الخصم",
  },
  "accountingreports-purchaseorders": {
    value: "القيمة",
    unitName: "وحده القياس",
    itemName: "الصنف",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    batchNumber: "رقم التشغيلة",
    discount: "الخصم",
  },
  "accountingreports-debitsages": {
    documentNumber: "مسلسل",
    customerName: "العميل",
    current: "اقل من",
    days30: "30",
    days60: "60",
    days90: "90",
    over90: "اكثر من",
    total: "الاجمالي",
  },
  "accountingreports-debitsagesbyyear": {
    documentNumber: "مسلسل",
    customerName: "العميل",
    total: "الاجمالي",
  },
  "accountingreports-debitsagesbyhalfyear": {
    documentNumber: "مسلسل",
    customerName: "العميل",
    over: "اكثر من",
    total: "الاجمالي",
  },
  // —— موجة 4: تحصيل / شيكات / استحقاقات / بقايا محاسبية — من PDF ميجا (artifacts/mega-wave4-collection) ——
  "accountingreports-checks-checkin": {
    documentNumber: "مسلسل",
    checkNumber: "رقم الشيك",
    bankName: "البنك المصدر",
    depositAccount: "الحساب المودع",
    amount: "المبلغ",
    date: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    status: "حالة الشيك",
    branchName: "الفرع",
    currency: "العملة",
  },
  "accountingreports-checks-checkout": {
    documentNumber: "مسلسل",
    checkNumber: "رقم الشيك",
    bankName: "البنك المصدر",
    depositAccount: "الحساب المودع",
    amount: "المبلغ",
    date: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    status: "حالة الشيك",
    branchName: "الفرع",
    currency: "العملة",
  },
  "accountingreports-customersinstallments": {
    documentNumber: "مسلسل",
    collectionDate: "تاريخ التحصيل",
    amount: "القيمة",
    repName: "المندوب",
    date: "التاريخ",
    customerName: "العميل",
    paid: "المدفوع",
    status: "الحالة",
  },
  "accountingreports-payments": {
    documentNumber: "مسلسل",
    invoiceRef: "م الفاتورة",
    repName: "المندوب",
    amount: "المبلغ",
    creditAccount: "الحساب الدائن",
    debitAccount: "الحساب المدين",
    voucherNumber: "رقم المستند",
    date: "التاريخ",
  },
  "accountingreports-dues": {
    documentNumber: "مسلسل",
    accountName: "الحساب",
    date: "التاريخ",
    amount: "القيمة",
    paid: "المدفوع",
    status: "الحالة",
    settlementDate: "تاريخ السداد",
  },
  "accountingreports-accountstatment-cash": {
    documentNumber: "رقم المستند",
    entryNumber: "رقم القيد",
    description: "الوصف",
    exchangeRate: "سعر الصرف",
    balance: "الرصيد",
    credit: "دائن",
    debit: "مدين",
    date: "التاريخ",
  },
  "accountingreports-costcenterstatment": {
    documentNumber: "رقم المستند",
    description: "الوصف",
    balance: "الرصيد",
    credit: "دائن",
    debit: "مدين",
    date: "التاريخ",
  },
  "accountingreports-dashboard": {
    name: "الاسم",
    currency: "العملة",
    balance: "الرصيد",
  },
  "accountingreports-branchessummary": {
    disbursement: "صرف",
    netSales: "صافى مبيعات",
    documentNumber: "مسلسل",
    netPurchases: "صافى مشتريات",
    cashBalance: "رصيد خزائن",
    collection: "تحصيل",
    salesReturns: "مردود مبيعات",
    sales: "مبيعات",
    branchName: "الفرع",
  },
  "accountingreports-monthlyexpenses": {
    accountName: "اسم الحساب",
    jan: "يناير",
    feb: "فبراير",
    mar: "مارس",
    apr: "ابريل",
    may: "مايو",
    jun: "يونيه",
    jul: "يوليو",
    aug: "اغسطس",
    sep: "سبتمبر",
    oct: "اكتوبر",
    nov: "نوفمبر",
    dec: "ديسمبر",
    total: "المجموع",
  },
  // Wave 5 — FinalReports statements (Mega PDF labels)
  "finalreports-salescost": {
    lineLabel: "البيان",
    amount: "المبلغ",
  },
  "finalreports-incomestatment": {
    lineLabel: "البيان",
    amount: "المبلغ",
  },
  "finalreports-balancesheet": {
    lineLabel: "البيان",
    amount: "المبلغ",
  },
  "finalreports-financialstatment": {
    lineLabel: "البيان",
    amount: "المبلغ",
  },
  "finalreports-cashflow": {
    lineLabel: "البيان",
    amount: "المبلغ",
  },
  "finalreports-subledger": {
    date: "التاريخ",
    documentNumber: "رقم المستند",
    accountCode: "كود الحساب",
    accountName: "اسم الحساب",
    description: "البيان",
    costCenter: "مركز التكلفة",
    debit: "مدين",
    credit: "دائن",
    balance: "الرصيد",
  },
  // موجة 6 — أرباح + أعمار دائنين (artifacts/mega-wave6-profits)
  "accountingreports-itemsprofits": {
    itemName: "الصنف",
    salesQty: "مبيعات",
    salesValue: "قيمة المبيعات",
    returnQty: "مردود",
    returnValue: "قيمة المردود",
    netSalesQty: "صافى مبيعات",
    netSalesValue: "صافى قيمة المبيعات",
    discounts: "خصومات",
    salesCost: "تكلفة مبيعات",
    returnCost: "تكلفة مردود",
    netSalesCost: "صافى تكلفة المبيعات",
    profit: "الربح",
    profitRatio: "نسبة الربحية",
  },
  "accountingreports-customersprofits": {
    serial: "مسلسل",
    areaName: "المنطقة",
    customerName: "العميل",
    netSales: "صافي المبيعات",
    profit: "الارباح",
    profitRatio: "نسبة الربحية",
  },
  "accountingreports-invoiceprofits": {
    serial: "المسلسل",
    date: "التاريخ",
    customerName: "العميل",
    gross: "الاجمالي",
    discount: "الخصم",
    tax: "الضرائب",
    additions: "اضافات",
    net: "الصافي",
    expenses: "المصروفات",
    profit: "الربح",
    profitRatio: "نسبة الربح",
  },
  // CreditsAges PDF blocked on test login — mirrored from DebitsAges Mega (wave2) with party=المورد
  "accountingreports-creditsages": {
    documentNumber: "مسلسل",
    supplierName: "المورد",
    current: "اقل من",
    days30: "30",
    days60: "60",
    days90: "90",
    over90: "اكثر من",
    total: "الاجمالي",
  },
  "accountingreports-creditsagesbyyear": {
    documentNumber: "مسلسل",
    supplierName: "المورد",
    total: "الاجمالي",
  },
  "accountingreports-creditsagesbyhalfyear": {
    documentNumber: "مسلسل",
    supplierName: "المورد",
    firstHalf: "اقل من",
    secondHalf: "اكثر من",
    over: "اكثر من",
    total: "الاجمالي",
  },
  // موجة 7 — مندوبين (artifacts/mega-wave7-reps)
  "accountingreports-grossrepsalesbyitems": {
    itemName: "الصنف",
    quantity: "الكمية",
    unitName: "وحده القياس",
    unitPrice: "سعر الوحدة",
    discount: "الخصم",
    total: "القيمة",
  },
  "accountingreports-repscollectings": {
    rowNum: "م",
    collectionDate: "تاريخ التحصيل",
    serial: "المسلسل",
    customerName: "اسم العميل",
    amount: "المبلغ",
    invoiceSerial: "مسلسل الفاتورة",
  },
  "accountingreports-repdaily": {
    serial: "مسلسل",
    repName: "المندوب",
    sales: "مبيعات",
    returns: "مردود",
    netSales: "صافي مبيعات",
    collection: "تحصيل",
    checkCollection: "تحصيل شيكات",
    totalCollection: "اجمالى التحصيل",
    debit: "المديونية",
    collectionCommission: "عمولة تحصيل",
    salesCommission: "عمولة بيع",
    profit: "ارباح",
    profitRatio: "نسبة الربحية",
  },
  "accountingreports-repdebit": {
    customerName: "العميل",
    sales: "مبيعات",
    returns: "مردود",
    collection: "تحصيل",
    checkCollection: "تحصيل شيكات",
    debit: "المديونية",
  },
  // موجة 8 — إنتاج (artifacts/mega-wave8-production)
  "accountingreports-productionorders": {
    lineLabel: "البيان",
    value: "القيمة",
    rawMaterial: "المادة الخام",
    barcode: "الباركود",
    quantity: "الكمية",
    scrapQty: "كمية تالف",
    unitName: "وحدة القياس",
    rawCost: "تكلفة خام",
    scrapCost: "تكلفة تالف",
    totalCost: "اجمالى تكلفة",
  },
  "accountingreports-productionmaterials": {
    warehouseName: "المخزن",
    barcode: "الباركود",
    itemName: "الصنف",
    batchNumber: "رقم التشغيلة",
    quantity: "الكمية",
    unitName: "وحدة القياس",
    cost: "التكلفة",
  },
  // موجة 9 — HR (artifacts/mega-wave9-hr)
  "hrreports-attendance": {
    date: "التاريخ",
    checkInTime: "وقت الحضور",
    checkOutTime: "وقت الانصراف",
    workHours: "ساعات العمل",
    permissionHours: "الاستئذان",
    missionPermissionHours: "الاستئذان بمهمة",
    delayHours: "تأخير",
    overtimeHours: "الوقت الاضافى",
    unknownHours: "غير معروف",
    noCheckIn: "بدون حضور",
    noCheckOut: "بدون انصراف",
    workOnLeave: "عمل فى اجازة",
    absenceMission: "الغياب بمهمه",
    vacationDays: "اجازة",
    partialVacationDays: "اجازة مستقطعة",
    weeklyVacationDays: "الاجازة الاسبوعية",
    officialVacationDays: "اجازة رسمية",
  },
  "hrreports-employeesvactions": {
    vacationType: "النوع",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    approved: "موافق عليها",
  },
  "hrreports-employeespayroll": {
    lineLabel: "البيان",
    value: "القيمة",
  },
  "hrreports-employeespayroll-list": {
    name: "الاسم",
    basicSalary: "الراتب الأساسي",
    advances: "السلف",
    workWithDeduction: "عمل بالخصم",
    tax: "الضرائب",
    insurance: "التأمينات",
    penaltyDeduction: "خصم العقوبات",
    lateDeduction: "خصم التأخير",
    permissionDeduction: "خصم الاستئذان",
    absenceDeduction: "خصم الغياب",
    otherDeductions: "خصومات أخرى",
    vacationWithDeduction: "الاجازات بالخصم",
    overtimeIncrease: "زيادة العمل الإضافي",
    holidayWork: "العمل بالاجازات",
    incentives: "الحوافز",
    otherIncreases: "زيادات أخرى",
    allowances: "البدلات",
    netSalary: "صافى الراتب",
  },
  "hrreports-employeesunderrequest": {
    name: "الاسم",
    nationalId: "الرقم القومي",
    jobTitle: "الوظيفة",
    qualityTestResult: "نتيجة الاختبار - الجودة",
    speedTestResult: "نتيجة الاختبار - السرعة",
    testDate: "تاريخ الاختبار",
    phone: "رقم التليفون",
    alternatePhone: "تليفون آخر",
  },
  "hrreports-employeeslist": {
    lineLabel: "البيان",
    value: "القيمة",
  },
  "hrreports-loans-list": {
    serial: "المسلسل",
    branchName: "الفرع",
    date: "التاريخ",
    startDate: "تاريخ البداية",
    amount: "المبلغ",
    creditAccount: "الحساب الدائن",
    installmentCount: "عدد الاقساط",
    installmentStatus: "حالة التقسيط",
    notes: "ملاحظات",
  },
  // موجة 10 — أصول (artifacts/mega-wave10-assets)
  "fixedassetsreports-dep": {
    name: "الاسم",
    currency: "العملة",
    exchangeRate: "سعر الصرف",
    purchaseDate: "تاريخ الشراء",
    operationDate: "تاريخ التشغيل",
    depreciationRate: "معدل الاهلاك",
    assetValue: "قيمة الاصل",
    depreciationAsOf: "الاهلاك فى",
    periodDepreciation: "اهلاك الفترة",
    accumulatedDepreciation: "مجمع الاهلاك",
    netBookValue: "القيمة بعد الاهلاك",
  },
  "fixedassetsreports-depruns": {
    name: "الاسم",
    currency: "العملة",
    exchangeRate: "سعر الصرف",
    purchaseDate: "تاريخ الشراء",
    operationDate: "تاريخ التشغيل",
    depreciationRate: "معدل الاهلاك",
    assetValue: "قيمة الاصل",
    depreciationAsOf: "الاهلاك فى",
    periodDepreciation: "اهلاك الفترة",
    accumulatedDepreciation: "مجمع الاهلاك",
    netBookValue: "القيمة بعد الاهلاك",
  },
  "fixedassetsreports-soldfixedassets": {
    name: "الاسم",
    assetValue: "قيمة الاصل",
    lastUsage: "اخر استخدام",
    saleDate: "تاريخ البيع",
    depreciation: "الاهلاك",
    salePrice: "سعر البيع",
    profitLoss: "الربح / الخسارة",
  },
};

export function reportColumnLabelForSlug(slug: string, key: string) {
  return MEGA_REPORT_COLUMN_LABELS[slug]?.[key] || reportColumnLabel(key);
}

/** أعمدة رقمية تُجمَّع في صف الإجمالي */
export const REPORT_TOTAL_COLUMNS = new Set([
  "salesQty", "salesValue", "returnQty", "returnValue", "netSalesQty", "netSalesValue", "discounts", "salesCost", "returnCost", "netSalesCost", "profit", "profitRatio", "netSales", "gross", "net", "expenses",

  "total", "subtotal", "discount", "tax", "additions", "expenses", "paid", "remaining", "amount",
  "salesQty", "purchaseQty", "returnQty", "unitPrice", "net",
  "sales", "salesReturns", "collections", "otherOps", "balanceToDate", "previousBalance", "netSales",
  "purchases", "purchaseReturns", "payments", "netPurchases",
  "lastSalePrice", "lastPurchasePrice", "lastSaleDiscount", "lastPurchaseDiscount",
  "invoiceNet", "collectedPaid", "returns", "netDue", "value", "current", "days30", "days60", "days90", "over90",
  "quantity", "profit", "commission", "foreignTotal", "balance",
  "totalSales", "totalPurchases", "totalPaid", "totalPaidCash", "totalCollected",
  "salesTotal", "salesPaid", "salesRemaining", "purchasesTotal", "collectionsTotal",
  "netSalesPurchases", "invoiceCount", "invoicesCount", "customersCount",
  "suppliersCount", "warehousesCount",
  "salesInvoicesCount", "purchasesInvoicesCount", "count", "collectionsCount",
  "costTotal",
  "debit", "credit", "value", "lineAmount", "totalAmount", "postedDepreciation",
  "bookAccumulated", "monthlyTheoretical", "purchasePrice", "currentValue",
  "bookValue", "saleAmount", "gainLoss",
  "openingDebit", "openingCredit", "periodDebit", "periodCredit",
  "closingDebit", "closingCredit",
  "disbursement", "netSales", "netPurchases", "cashBalance", "collection",
  "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec",
  "returns", "netSales", "collection", "checkCollection", "totalCollection",
  "collectionCommission", "salesCommission", "profitRatio", "invoiceSerial",
  "rawCost", "scrapCost", "totalCost", "scrapQty", "cost", "assetValue",
  "depreciationAsOf", "periodDepreciation", "accumulatedDepreciation", "netBookValue",
  "depreciation", "salePrice", "profitLoss", "basicSalary", "advances", "workWithDeduction",
  "insurance", "penaltyDeduction", "lateDeduction", "permissionDeduction", "absenceDeduction",
  "otherDeductions", "vacationWithDeduction", "overtimeIncrease", "holidayWork", "incentives",
  "otherIncreases", "allowances", "netSalary", "workHours", "overtimeHours",
]);
